name:                vessel
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/vessel#readme
license:             MIT
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
- README.md
build-tools:         hsc2hs
dependencies:
  - base >= 4.7 && < 5
  - wreq == 0.5.0.1
  - process == 1.4.3.0
  - unix == 2.7.2.1
  - filepath == 1.4.1.1
  - directory == 1.3.0.0
  - lens == 4.15.1
  - bytestring == 0.10.8.1
  - lens-aeson == 1.0.1
  - text == 1.2.2.1
  - monad-logger == 0.3.24
  - mtl == 2.2.1
  - optparse-applicative == 0.13.2.0
  - optparse-text == 0.1.1.0
  - linux-mount == 0.2.0.1
executables:
  vessel:
    source-dirs:      src
    main:             Main.hs
