name:                vessel
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/vessel#readme
license:             MIT
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - wreq == 0.5.0.1
  - tar == 0.5.0.3
executables:
  vessel:
    source-dirs:      src
    main:             Main.hs
